export const REGISTER_USER="REGISTER_USER"
export const LOGIN_USER="LOGIN_USER"
export const LOGOUT_USER="LOGOUT_USER"
export const EMAIL_VERIFICATION="EMAIL_VERIFICATION"
export const FORGOT_PASSWORD="FORGOT_PASSWORD"
export const FORGOT_PASSWORD_LINK="FORGOT_PASSWORD_LINK"


export const REGISTER_ADMIN="REGISTER_ADMIN"
export const LOGIN_ADMIN="LOGIN_ADMIN"
export const LOGOUT_ADMIN="LOGOUT_ADMIN"
export const Add_MOVIE="Add_MOVIE"
